import assert from "node:assert/strict";
import { appendFileSync, mkdtempSync, readdirSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
process.env.PI_CODING_AGENT_DIR = mkdtempSync(join(tmpdir(), "pi-web-runs-"));
const { appendRunRecord, readRunRecords, rotateRunRecords } = await (await import("jiti")).createJiti(import.meta.url).import("./run-registry.ts");
const usage = { input: 1, output: 2, cacheRead: 0, cacheWrite: 0, cost: 0, turns: 1, toolCalls: 0 };
test("append is one 0600 line per run; read filters by agent and since, skips junk; rotation renames past the cap", () => {
  const path = join(mkdtempSync(join(tmpdir(), "r-")), "runs.jsonl");
  appendRunRecord({ ts: "2026-10-07T01:00:00.000Z", agent: "a", origin: "trigger", status: "completed", usage, billing: "unknown" }, path);
  appendRunRecord({ ts: "2026-10-07T02:00:00.000Z", agent: "b", origin: "user", status: "completed", usage, billing: "unknown" }, path);
  appendFileSync(path, "not json\n");
  assert.equal(statSync(path).mode & 0o777, 0o600);
  assert.equal(readRunRecords({ path }).length, 2);
  assert.deepEqual(readRunRecords({ path, agent: "a" }).map((r) => r.ts), ["2026-10-07T01:00:00.000Z"]);
  assert.equal(readRunRecords({ path, since: "2026-10-07T01:30:00.000Z" }).length, 1);
  rotateRunRecords(10, path);
  assert.equal(readRunRecords({ path }).length, 0);
  assert.ok(readdirSync(dirname(path)).some((f) => /^runs\..+\.jsonl$/.test(f)), "rotated file exists beside runs.jsonl");
});
