import assert from "node:assert/strict";
import { test } from "node:test";
import { existsSync, mkdtempSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
process.env.PI_CODING_AGENT_DIR = mkdtempSync(join(tmpdir(), "agentops-trigger-api-")); // before the imports
const jiti = (await import("jiti")).createJiti(import.meta.url);
const api = await jiti.import("./trigger-api.ts");
const store = await jiti.import("./trigger-store.ts");
const reg = await jiti.import("../agents/registry.ts");

const cwd = process.env.PI_CODING_AGENT_DIR;
const base = { name: "nightly", profile: "apia", promptTemplate: "check" };
const create = (extra = {}) => api.createTriggerFromInput({ ...base, ...extra });

function globalProfile(name) {
  reg.createLongTermAgent({ name, role: "Do the job.", toolsPreset: "standard", avatar: { emoji: "x", color: "#aaaaaa" } });
  return reg.resolveLongTermProfile(name).filePath;
}
const edit = (name) => reg.updateLongTermAgent(name, { role: `Changed ${Math.random()}` });
globalProfile("apia");

test("toPublicTrigger never carries the secret and flags its presence", () => {
  const view = api.toPublicTrigger({ id: "x", webhookSecretSha256: "ab".repeat(32), name: "n" });
  assert.equal("webhookSecretSha256" in view, false);
  assert.equal(view.hasWebhookSecret, true);
  const legacy = api.toPublicTrigger({ id: "z", webhookSecret: "hush", name: "n" }); // old plaintext file: never leaves, never counts
  assert.equal("webhookSecret" in legacy, false);
  assert.equal(legacy.hasWebhookSecret, false);
  assert.equal(api.toPublicTrigger({ id: "y" }).hasWebhookSecret, false);
});

test("create without webhook: stored, public, no secret", () => {
  const result = create();
  assert.equal(result.ok, true);
  assert.equal(result.webhookSecret, undefined);
  assert.equal(result.trigger.hasWebhookSecret, false);
  assert.equal(store.getTrigger(result.trigger.id).webhookSecretSha256, undefined);
});

test("create with webhook returns a fresh server secret once; the list hides it", () => {
  const result = create({ webhook: true });
  assert.equal(result.ok, true);
  assert.match(result.webhookSecret, /^[A-Za-z0-9_-]{43}$/);
  assert.equal(result.trigger.hasWebhookSecret, true);
  assert.equal(JSON.stringify(result.trigger).includes(result.webhookSecret), false);
  const stored = store.getTrigger(result.trigger.id);
  assert.equal(stored.webhookSecretSha256, store.hashWebhookSecret(result.webhookSecret));
  assert.equal("webhookSecret" in stored, false);
  assert.equal(readFileSync(join(cwd, "agent-ops", "triggers", `${result.trigger.id}.json`), "utf8").includes(result.webhookSecret), false);
  const listed = api.listPublicTriggers();
  assert.equal(JSON.stringify(listed).includes(result.webhookSecret), false);
  assert.equal(listed.find((t) => t.id === result.trigger.id).hasWebhookSecret, true);
  assert.notEqual(create({ webhook: true }).webhookSecret, result.webhookSecret);
});

test("create refuses a client-supplied secret, non-boolean webhook/enabled, bad profile, non-object", () => {
  const refused = (input, pattern, status = 400) => {
    const result = api.createTriggerFromInput(input);
    assert.equal(result.ok, false);
    assert.equal(result.status, status);
    assert.match(result.error, pattern);
  };
  refused({ ...base, webhookSecret: "mine" }, /generated by the server/);
  refused({ ...base, webhook: "yes" }, /webhook must be a boolean/);
  refused({ ...base, enabled: "true" }, /enabled must be a boolean/);
  refused({ ...base, profile: "explore" }, /profile not found/); // a built-in is not a long-term agent
  refused({ ...base, profile: "ghost" }, /profile not found/);
  refused({ ...base, name: " " }, /name is required/);
  refused(null, /Invalid/);
  refused([], /Invalid/);
  assert.equal(api.listPublicTriggers().some((t) => t.name === " "), false);
});

test("create ignores cwd; patch refuses it as an unknown field", () => {
  const result = create({ cwd: "/tmp/elsewhere" });
  assert.equal(result.ok, true);
  assert.equal("cwd" in store.getTrigger(result.trigger.id), false);
  assert.match(api.patchTrigger(result.trigger.id, { cwd: "/tmp" }).error, /unknown field: cwd/);
});

test("create ignores fields outside the contract (id, pinnedProfile)", () => {
  const result = create({ id: "00000000-0000-4000-8000-0000000000aa", pinnedProfile: { contentSha256: "x" } });
  assert.notEqual(result.trigger.id, "00000000-0000-4000-8000-0000000000aa");
  assert.notEqual(result.trigger.pinnedProfile.contentSha256, "x");
});

test("rotate replaces the secret, returns it once, and the old one is gone", () => {
  const created = create({ webhook: true });
  const rotated = api.rotateSecret(created.trigger.id);
  assert.equal(rotated.ok, true);
  assert.notEqual(rotated.webhookSecret, created.webhookSecret);
  assert.equal(store.getTrigger(created.trigger.id).webhookSecretSha256, store.hashWebhookSecret(rotated.webhookSecret));
  assert.equal(JSON.stringify(rotated.trigger).includes(rotated.webhookSecret), false);
});

test("rotate drops a legacy plaintext webhookSecret and stores the digest", () => {
  const created = create();
  store.saveTrigger({ ...store.getTrigger(created.trigger.id), webhookSecret: "old-plaintext" });
  const rotated = api.rotateSecret(created.trigger.id);
  const stored = store.getTrigger(created.trigger.id);
  assert.equal("webhookSecret" in stored, false);
  assert.equal(stored.webhookSecretSha256, store.hashWebhookSecret(rotated.webhookSecret));
});

test("rotate gives a secret to a trigger that had none, and drops its throttle state", () => {
  const created = create();
  globalThis.__agentOpsHookThrottles = new Map([[created.trigger.id, {}]]);
  const rotated = api.rotateSecret(created.trigger.id);
  assert.equal(rotated.trigger.hasWebhookSecret, true);
  assert.equal(globalThis.__agentOpsHookThrottles.has(created.trigger.id), false);
});

test("rotate and patch answer 404 for unknown or invalid ids", () => {
  for (const id of ["00000000-0000-4000-8000-0000000000ff", "../etc", "nope"]) {
    assert.deepEqual(api.rotateSecret(id), { ok: false, status: 404, error: "Trigger not found" });
    assert.deepEqual(api.patchTrigger(id, { enabled: false }), { ok: false, status: 404, error: "Trigger not found" });
  }
});

test("patch toggles enabled and edits fields, keeping id, secret and pin", () => {
  const created = create({ webhook: true });
  const before = store.getTrigger(created.trigger.id);
  const patched = api.patchTrigger(before.id, { enabled: false, name: "renamed", promptTemplate: "p2", everyMinutes: 10, dedupWindowMs: 1000, maxActiveTasks: 3 });
  assert.equal(patched.ok, true);
  assert.equal("webhookSecretSha256" in patched.trigger, false);
  assert.equal(patched.trigger.hasWebhookSecret, true);
  const after = store.getTrigger(before.id);
  assert.deepEqual(after, { ...before, enabled: false, name: "renamed", promptTemplate: "p2", everyMinutes: 10, dedupWindowMs: 1000, maxActiveTasks: 3 });
});

test("patch everyMinutes: null removes the schedule", () => {
  const created = create({ everyMinutes: 5 });
  const patched = api.patchTrigger(created.trigger.id, { everyMinutes: null });
  assert.equal(patched.ok, true);
  assert.equal("everyMinutes" in store.getTrigger(created.trigger.id), false);
});

test("create refuses null limits and a null schedule instead of defaulting them", () => {
  for (const field of ["dedupWindowMs", "maxActiveTasks", "everyMinutes"]) {
    const result = create({ [field]: null });
    assert.equal(result.ok, false);
    assert.match(result.error, new RegExp(`${field} must be a number`));
  }
});

test("patch refuses non-boolean enabled, invalid numbers, a secret and unknown fields; nothing is written", () => {
  const created = create({ webhook: true });
  const before = store.getTrigger(created.trigger.id);
  const refused = (body, pattern) => {
    const result = api.patchTrigger(before.id, body);
    assert.equal(result.ok, false);
    assert.equal(result.status, 400);
    assert.match(result.error, pattern);
  };
  refused({ enabled: "false" }, /enabled must be a boolean/);
  refused({ enabled: null }, /enabled must be a boolean/);
  refused({ maxActiveTasks: 0 }, /maxActiveTasks/);
  refused({ dedupWindowMs: -1 }, /dedupWindowMs/);
  refused({ everyMinutes: 0 }, /everyMinutes/);
  refused({ dedupWindowMs: null }, /dedupWindowMs must be a number/);
  refused({ maxActiveTasks: null }, /maxActiveTasks must be a number/);
  refused({ dedupWindowMs: "5" }, /dedupWindowMs/);
  refused({ name: "" }, /name is required/);
  refused({ webhookSecret: "mine" }, /webhookSecret/);
  refused({ id: "00000000-0000-4000-8000-0000000000ab" }, /unknown field: id/);
  refused({ pinnedProfile: {} }, /unknown field: pinnedProfile/);
  refused([], /Invalid/);
  assert.deepEqual(store.getTrigger(before.id), before);
});

test("patch can still toggle a trigger whose profile vanished, without re-pinning", () => {
  globalProfile("vanishing");
  const created = create({ profile: "vanishing" });
  assert.equal(created.ok, true);
  const pin = store.getTrigger(created.trigger.id).pinnedProfile;
  edit("vanishing");
  const patched = api.patchTrigger(created.trigger.id, { enabled: false });
  assert.equal(patched.ok, true);
  assert.deepEqual(store.getTrigger(created.trigger.id).pinnedProfile, pin);
});

test("patch re-pins when the profile changes and refuses a profile that is not a long-term agent", () => {
  const filePath = globalProfile("reader");
  const created = create();
  const planPin = store.getTrigger(created.trigger.id).pinnedProfile;
  const patched = api.patchTrigger(created.trigger.id, { profile: "reader" });
  assert.equal(patched.ok, true);
  const after = store.getTrigger(created.trigger.id);
  assert.equal(after.profile, "reader");
  assert.notDeepEqual(after.pinnedProfile, planPin);
  assert.equal(after.pinnedProfile.filePath, filePath);
  const refused = api.patchTrigger(created.trigger.id, { profile: "explore" });
  assert.equal(refused.ok, false);
  assert.match(refused.error, /profile not found/);
  assert.equal(store.getTrigger(created.trigger.id).profile, "reader");
});

test("pinStatus: ok, drift after the profile file changes, missing once it is gone; every public view carries it", () => {
  const filePath = globalProfile("watched");
  const created = create({ profile: "watched" });
  const status = () => api.listPublicTriggers().find((t) => t.id === created.trigger.id).pinStatus;
  assert.equal(created.trigger.pinStatus, "ok");
  assert.equal(status(), "ok");
  edit("watched");
  assert.equal(status(), "drift");
  unlinkSync(filePath);
  assert.equal(status(), "missing");
});

test("repin stores the new sha and clears the drift; other fields are untouched", () => {
  const filePath = globalProfile("repinned");
  const created = create({ profile: "repinned", webhook: true });
  const before = store.getTrigger(created.trigger.id);
  edit("repinned");
  assert.equal(api.listPublicTriggers().find((t) => t.id === before.id).pinStatus, "drift");
  const result = api.patchTrigger(before.id, { repin: true });
  assert.equal(result.ok, true);
  assert.equal(result.trigger.pinStatus, "ok");
  const after = store.getTrigger(before.id);
  assert.notEqual(after.pinnedProfile.contentSha256, before.pinnedProfile.contentSha256);
  assert.equal(after.pinnedProfile.contentSha256, store.profilePinSha256({ filePath }));
  assert.deepEqual({ ...after, pinnedProfile: before.pinnedProfile }, before);
});

test("repin is refused when the profile is gone or repin is not a boolean; the pin stays", () => {
  const filePath = globalProfile("hardened");
  const created = create({ profile: "hardened" });
  const before = store.getTrigger(created.trigger.id);
  assert.equal(api.patchTrigger(before.id, { repin: "yes" }).ok, false);
  unlinkSync(filePath);
  const gone = api.patchTrigger(before.id, { repin: true });
  assert.equal(gone.ok, false);
  assert.match(gone.error, /profile not found/);
  assert.deepEqual(store.getTrigger(before.id), before);
});

test("repinTriggersOfAgent renews the pins of that agent's triggers only; a vanished profile keeps its pin", () => {
  globalProfile("pinned");
  globalProfile("bystander");
  const mine = [create({ profile: "pinned" }), create({ profile: "pinned", name: "second" })].map((r) => r.trigger.id);
  const other = create({ profile: "bystander" }).trigger.id;
  const before = Object.fromEntries([...mine, other].map((id) => [id, store.getTrigger(id).pinnedProfile.contentSha256]));
  edit("pinned");
  edit("bystander");
  assert.equal(api.listPublicTriggers().find((t) => t.id === mine[0]).pinStatus, "drift");
  assert.equal(api.repinTriggersOfAgent("pinned"), 2);
  for (const id of mine) {
    assert.notEqual(store.getTrigger(id).pinnedProfile.contentSha256, before[id]);
    assert.equal(api.listPublicTriggers().find((t) => t.id === id).pinStatus, "ok");
  }
  assert.equal(store.getTrigger(other).pinnedProfile.contentSha256, before[other]);
  unlinkSync(reg.resolveLongTermProfile("pinned").filePath);
  const kept = store.getTrigger(mine[0]).pinnedProfile;
  assert.equal(api.repinTriggersOfAgent("pinned"), 0);
  assert.deepEqual(store.getTrigger(mine[0]).pinnedProfile, kept);
});

test("deleteTriggersOfAgent removes only that agent's triggers", () => {
  globalProfile("doomed");
  globalProfile("survivor");
  const doomed = [create({ profile: "doomed" }), create({ profile: "doomed" })].map((r) => r.trigger.id);
  const survivor = create({ profile: "survivor" }).trigger.id;
  assert.equal(api.deleteTriggersOfAgent("doomed"), 2);
  for (const id of doomed) assert.equal(store.getTrigger(id), null);
  assert.ok(store.getTrigger(survivor));
  assert.equal(api.deleteTriggersOfAgent("doomed"), 0);
});

test("deleteTriggerById removes it, 404 afterwards", () => {
  const created = create();
  assert.equal(api.deleteTriggerById(created.trigger.id).ok, true);
  assert.deepEqual(api.deleteTriggerById(created.trigger.id), { ok: false, status: 404, error: "Trigger not found" });
  assert.equal(api.listPublicTriggers().some((t) => t.id === created.trigger.id), false);
});

test("triggerResponse: no-store JSON without the ok flag, secret only where the result carries it, errors with their status", async () => {
  const created = create({ webhook: true });
  const response = api.triggerResponse(created, 201);
  assert.equal(response.status, 201);
  assert.equal(response.headers.get("cache-control"), "no-store");
  const body = await response.json();
  assert.deepEqual(Object.keys(body).sort(), ["trigger", "webhookSecret"]);
  const patched = await api.triggerResponse(api.patchTrigger(created.trigger.id, { enabled: false })).json();
  assert.deepEqual(Object.keys(patched), ["trigger"]);
  const missing = api.triggerResponse(api.rotateSecret("nope"));
  assert.equal(missing.status, 404);
  assert.deepEqual(await missing.json(), { error: "Trigger not found" });
});

test("feed source: https URL and everyMinutes required, never a webhook", () => {
  const source = { kind: "feed", url: "https://example.com/feed.xml" };
  const ok = create({ source, everyMinutes: 30 });
  assert.equal(ok.ok, true);
  assert.deepEqual(store.getTrigger(ok.trigger.id).source, source);
  for (const bad of [{ kind: "feed", url: "http://example.com/f" }, { kind: "feed", url: "https://u:p@example.com/f" }, { kind: "feed", url: `https://e.com/${"a".repeat(2100)}` }, { kind: "feed", url: "nope" }, { kind: "rss", url: "https://e.com" }, null]) {
    const result = create({ source: bad, everyMinutes: 30 });
    assert.equal(result.ok, false, JSON.stringify(bad));
    assert.equal(result.status, 400);
  }
  assert.match(create({ source }).error, /everyMinutes/);
  assert.match(create({ source, everyMinutes: 30, webhook: true }).error, /webhook/);
  assert.match(api.rotateSecret(ok.trigger.id).error, /webhook/);
  assert.equal(api.patchTrigger(ok.trigger.id, { source: { kind: "feed", url: "http://e.com" } }).status, 400);
  assert.equal(api.patchTrigger(ok.trigger.id, { everyMinutes: null }).status, 400);
});

test("patching the feed URL clears the poll state; deleting the trigger removes it", () => {
  const made = create({ source: { kind: "feed", url: "https://example.com/a.xml" }, everyMinutes: 30 });
  const file = join(store.triggersDir(), `${made.trigger.id}.feed.json`);
  writeFileSync(file, '{"seen":["a"]}');
  api.patchTrigger(made.trigger.id, { name: "renamed" });
  assert.equal(existsSync(file), true);
  api.patchTrigger(made.trigger.id, { source: { kind: "feed", url: "https://example.com/b.xml" } });
  assert.equal(existsSync(file), false);
  writeFileSync(file, '{"seen":["a"]}');
  api.deleteTriggerById(made.trigger.id);
  assert.equal(existsSync(file), false);
});
