import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
process.env.PI_CODING_AGENT_DIR = mkdtempSync(join(tmpdir(), "agentops-trigger-api-")); // before the imports
const jiti = (await import("jiti")).createJiti(import.meta.url);
const api = await jiti.import("./trigger-api.ts");
const store = await jiti.import("./trigger-store.ts");

const cwd = process.env.PI_CODING_AGENT_DIR;
const base = { name: "nightly", profile: "plan", cwd, promptTemplate: "check" };
const create = (extra = {}) => api.createTriggerFromInput({ ...base, ...extra });

function globalProfile(name, tools = "read") {
  mkdirSync(join(cwd, "agents"), { recursive: true });
  const filePath = join(cwd, "agents", `${name}.md`);
  writeFileSync(filePath, `---\nname: ${name}\ndescription: test\ntools: ${tools}\n---\nDo the job.`);
  return filePath;
}

test("toPublicTrigger never carries the secret and flags its presence", () => {
  const trigger = { id: "x", webhookSecret: "hush", name: "n" };
  const view = api.toPublicTrigger(trigger);
  assert.equal("webhookSecret" in view, false);
  assert.equal(view.hasWebhookSecret, true);
  assert.equal(api.toPublicTrigger({ id: "y" }).hasWebhookSecret, false);
});

test("create without webhook: stored, public, no secret", () => {
  const result = create();
  assert.equal(result.ok, true);
  assert.equal(result.webhookSecret, undefined);
  assert.equal(result.trigger.hasWebhookSecret, false);
  assert.equal(store.getTrigger(result.trigger.id).webhookSecret, undefined);
});

test("create with webhook returns a fresh server secret once; the list hides it", () => {
  const result = create({ webhook: true });
  assert.equal(result.ok, true);
  assert.match(result.webhookSecret, /^[A-Za-z0-9_-]{43}$/);
  assert.equal(result.trigger.hasWebhookSecret, true);
  assert.equal(JSON.stringify(result.trigger).includes(result.webhookSecret), false);
  assert.equal(store.getTrigger(result.trigger.id).webhookSecret, result.webhookSecret);
  const listed = api.listPublicTriggers();
  assert.equal(JSON.stringify(listed).includes(result.webhookSecret), false);
  assert.equal(listed.find((t) => t.id === result.trigger.id).hasWebhookSecret, true);
  assert.notEqual(create({ webhook: true }).webhookSecret, result.webhookSecret);
});

test("create refuses a client-supplied secret, non-boolean webhook/enabled, bad cwd, bad profile, non-object", () => {
  const refused = (input, pattern, status = 400) => {
    const result = api.createTriggerFromInput(input);
    assert.equal(result.ok, false);
    assert.equal(result.status, status);
    assert.match(result.error, pattern);
  };
  refused({ ...base, webhookSecret: "mine" }, /generated by the server/);
  refused({ ...base, webhook: "yes" }, /webhook must be a boolean/);
  refused({ ...base, enabled: "true" }, /enabled must be a boolean/);
  refused({ ...base, cwd: join(cwd, "missing") }, /does not exist/);
  refused({ ...base, profile: "ghost" }, /profile not found/);
  refused({ ...base, name: " " }, /name is required/);
  refused(null, /Invalid/);
  refused([], /Invalid/);
  assert.equal(api.listPublicTriggers().some((t) => t.name === " "), false);
});

test("create ignores fields outside the contract (id, pinnedProfile)", () => {
  const result = create({ id: "00000000-0000-4000-8000-0000000000aa", pinnedProfile: { contentSha256: "x" } });
  assert.notEqual(result.trigger.id, "00000000-0000-4000-8000-0000000000aa");
  assert.notEqual(result.trigger.pinnedProfile.contentSha256, "x");
});

test("rotate replaces the secret, returns it once, and the old one is gone", () => {
  const created = create({ webhook: true });
  const rotated = api.rotateSecret(created.trigger.id);
  assert.equal(rotated.ok, true);
  assert.notEqual(rotated.webhookSecret, created.webhookSecret);
  assert.equal(store.getTrigger(created.trigger.id).webhookSecret, rotated.webhookSecret);
  assert.equal(JSON.stringify(rotated.trigger).includes(rotated.webhookSecret), false);
});

test("rotate gives a secret to a trigger that had none, and drops its throttle state", () => {
  const created = create();
  globalThis.__agentOpsHookThrottles = new Map([[created.trigger.id, {}]]);
  const rotated = api.rotateSecret(created.trigger.id);
  assert.equal(rotated.trigger.hasWebhookSecret, true);
  assert.equal(globalThis.__agentOpsHookThrottles.has(created.trigger.id), false);
});

test("rotate and patch answer 404 for unknown or invalid ids", () => {
  for (const id of ["00000000-0000-4000-8000-0000000000ff", "../etc", "nope"]) {
    assert.deepEqual(api.rotateSecret(id), { ok: false, status: 404, error: "Trigger not found" });
    assert.deepEqual(api.patchTrigger(id, { enabled: false }), { ok: false, status: 404, error: "Trigger not found" });
  }
});

test("patch toggles enabled and edits fields, keeping id, secret and pin", () => {
  const created = create({ webhook: true });
  const before = store.getTrigger(created.trigger.id);
  const patched = api.patchTrigger(before.id, { enabled: false, name: "renamed", promptTemplate: "p2", everyMinutes: 10, dedupWindowMs: 1000, maxActiveTasks: 3 });
  assert.equal(patched.ok, true);
  assert.equal("webhookSecret" in patched, false);
  assert.equal(JSON.stringify(patched.trigger).includes(before.webhookSecret), false);
  const after = store.getTrigger(before.id);
  assert.deepEqual(after, { ...before, enabled: false, name: "renamed", promptTemplate: "p2", everyMinutes: 10, dedupWindowMs: 1000, maxActiveTasks: 3 });
});

test("patch everyMinutes: null removes the schedule", () => {
  const created = create({ everyMinutes: 5 });
  const patched = api.patchTrigger(created.trigger.id, { everyMinutes: null });
  assert.equal(patched.ok, true);
  assert.equal("everyMinutes" in store.getTrigger(created.trigger.id), false);
});

test("patch refuses non-boolean enabled, invalid numbers, a secret and unknown fields; nothing is written", () => {
  const created = create({ webhook: true });
  const before = store.getTrigger(created.trigger.id);
  const refused = (body, pattern) => {
    const result = api.patchTrigger(before.id, body);
    assert.equal(result.ok, false);
    assert.equal(result.status, 400);
    assert.match(result.error, pattern);
  };
  refused({ enabled: "false" }, /enabled must be a boolean/);
  refused({ enabled: null }, /enabled must be a boolean/);
  refused({ maxActiveTasks: 0 }, /maxActiveTasks/);
  refused({ dedupWindowMs: -1 }, /dedupWindowMs/);
  refused({ everyMinutes: 0 }, /everyMinutes/);
  refused({ name: "" }, /name is required/);
  refused({ webhookSecret: "mine" }, /webhookSecret/);
  refused({ id: "00000000-0000-4000-8000-0000000000ab" }, /unknown field: id/);
  refused({ pinnedProfile: {} }, /unknown field: pinnedProfile/);
  refused([], /Invalid/);
  assert.deepEqual(store.getTrigger(before.id), before);
});

test("patch can still toggle a trigger whose profile vanished, without re-pinning", () => {
  globalProfile("vanishing");
  const created = create({ profile: "vanishing" });
  assert.equal(created.ok, true);
  const pin = store.getTrigger(created.trigger.id).pinnedProfile;
  writeFileSync(join(cwd, "agents", "vanishing.md"), "---\nname: vanishing\ndescription: edited\ntools: read\n---\nChanged.");
  const patched = api.patchTrigger(created.trigger.id, { enabled: false });
  assert.equal(patched.ok, true);
  assert.deepEqual(store.getTrigger(created.trigger.id).pinnedProfile, pin);
});

test("patch re-pins when the profile changes and refuses a profile outside the allowlist", () => {
  const filePath = globalProfile("reader");
  globalProfile("shell", "read, bash");
  const created = create();
  const planPin = store.getTrigger(created.trigger.id).pinnedProfile;
  const patched = api.patchTrigger(created.trigger.id, { profile: "reader" });
  assert.equal(patched.ok, true);
  const after = store.getTrigger(created.trigger.id);
  assert.equal(after.profile, "reader");
  assert.notDeepEqual(after.pinnedProfile, planPin);
  assert.equal(after.pinnedProfile.filePath, filePath);
  const refused = api.patchTrigger(created.trigger.id, { profile: "shell" });
  assert.equal(refused.ok, false);
  assert.match(refused.error, /found: bash/);
  assert.equal(store.getTrigger(created.trigger.id).profile, "reader");
});

test("patch re-resolves and re-pins when the cwd changes; the new cwd must exist", () => {
  const created = create();
  const other = mkdtempSync(join(tmpdir(), "agentops-trigger-cwd-"));
  assert.equal(api.patchTrigger(created.trigger.id, { cwd: other }).ok, true);
  assert.equal(store.getTrigger(created.trigger.id).cwd, other);
  const missing = api.patchTrigger(created.trigger.id, { cwd: join(other, "nope") });
  assert.equal(missing.ok, false);
  assert.match(missing.error, /does not exist/);
});

test("deleteTriggerById removes it, 404 afterwards", () => {
  const created = create();
  assert.equal(api.deleteTriggerById(created.trigger.id).ok, true);
  assert.deepEqual(api.deleteTriggerById(created.trigger.id), { ok: false, status: 404, error: "Trigger not found" });
  assert.equal(api.listPublicTriggers().some((t) => t.id === created.trigger.id), false);
});

test("triggerResponse: no-store JSON without the ok flag, secret only where the result carries it, errors with their status", async () => {
  const created = create({ webhook: true });
  const response = api.triggerResponse(created, 201);
  assert.equal(response.status, 201);
  assert.equal(response.headers.get("cache-control"), "no-store");
  const body = await response.json();
  assert.deepEqual(Object.keys(body).sort(), ["trigger", "webhookSecret"]);
  const patched = await api.triggerResponse(api.patchTrigger(created.trigger.id, { enabled: false })).json();
  assert.deepEqual(Object.keys(patched), ["trigger"]);
  const missing = api.triggerResponse(api.rotateSecret("nope"));
  assert.equal(missing.status, 404);
  assert.deepEqual(await missing.json(), { error: "Trigger not found" });
});
