// The 8 ANSI colors keep distinct hues (git diff, ls and compilers encode meaning in them),
// tuned to the Tron family: cyan, orange and red come from the UI tokens.
export const TRON_TERMINAL_THEME = {
  background: "#000000",
  foreground: "#dff6ff",
  cursor: "#00d8ff",
  cursorAccent: "#000000",
  selectionBackground: "rgba(0, 216, 255, 0.3)",
  black: "#0a1a22",
  red: "#ff4d5e",
  green: "#2ef2b0",
  yellow: "#ff9a00",
  blue: "#4f9dff",
  magenta: "#ff4dc4",
  cyan: "#00d8ff",
  white: "#dff6ff",
  brightBlack: "#5b8a9a",
  brightRed: "#ff7a87",
  brightGreen: "#7dffd0",
  brightYellow: "#ffbf66",
  brightBlue: "#8cc0ff",
  brightMagenta: "#ff8fdc",
  brightCyan: "#7fe9ff",
  brightWhite: "#ffffff",
};
